### ISSUE TITLE
Does this plugin works for amplify v4.32.1 ?

### ISSUE THREAD

**Issue by yaquawa** [trek10inc/graphql-default-value-transformer#3]
Hi, thanks for the great work!
I'm wondering if this plugin still works for the latest amplify v4.32.1 ?
I know very little about amplify plugin, the doc
https://docs.amplify.aws/cli/plugins/authoring#step-5-install-and-use
says you can install a plugin by 

```
amplify plugin add my-amplify-plugin
```

is this the right way to install this plugin?

**Comment by mjza** [comment]
@yaquawa I found the solution. 
Inside the AWS Amplify Console, edit your build settings, and change it like the following:

```
backend:
  phases:
    build:
      commands:
        - npm i -g graphql-default-value-transformer
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
```

I mean before `amplifyPush --simple` you need to provide the `npm i -g graphql-default-value-transformer` to install the custom transformer before doing the `amplifyPush`.
